<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Asus" name="com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest" tests="4" failures="1" timestamp="05 Jun 2019 20:02:40 GMT" time="0.000" errors="0">
  <testcase name="powTest" time="0.000" classname="com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of sinus expected [4.0] but found [13.92]">
      <![CDATA[java.lang.AssertionError: Invalid result of sinus expected [4.0] but found [13.92]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEquals(Assert.java:489)
at com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest.powTest(PowerCalculatorTest.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- powTest -->
  <testcase name="powTest" time="0.000" classname="com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest"/>
  <testcase name="powTest" time="0.000" classname="com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest"/>
  <testcase name="powTest" time="0.000" classname="com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest"/>
</testsuite> <!-- com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest -->
