<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Asus" ignored="0" name="Power Cal Test" tests="4" failures="1" timestamp="05 Jun 2019 20:02:38 GMT" time="0.708" errors="0">
  <testcase name="powTest" time="0.0" classname="com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest"/>
  <testcase name="powTest" time="0.0" classname="com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest"/>
  <testcase name="powTest" time="0.0" classname="com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest"/>
  <testcase name="powTest" time="0.0" classname="com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of sinus expected [4.0] but found [13.92]">
      <![CDATA[java.lang.AssertionError: Invalid result of sinus expected [4.0] but found [13.92]
at com.epam.cdp.cal.tests.testng.positive.PowerCalculatorTest.powTest(PowerCalculatorTest.java:12)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- powTest -->
</testsuite> <!-- Power Cal Test -->
