<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPBYMINW2706" ignored="0" name="Power Cal Test" tests="4" failures="1" timestamp="28 May 2019 12:49:23 GMT" time="0.316" errors="0">
  <testcase name="powTest" time="0.0" classname="com.epam.cdp.cal.tests.PowerCalculatorTest"/>
  <testcase name="powTest" time="0.0" classname="com.epam.cdp.cal.tests.PowerCalculatorTest"/>
  <testcase name="powTest" time="0.0" classname="com.epam.cdp.cal.tests.PowerCalculatorTest"/>
  <testcase name="powTest" time="0.0" classname="com.epam.cdp.cal.tests.PowerCalculatorTest">
    <failure type="java.lang.AssertionError" message="Invalid result of sinus expected [4.0] but found [13.92]">
      <![CDATA[java.lang.AssertionError: Invalid result of sinus expected [4.0] but found [13.92]
at com.epam.cdp.cal.tests.PowerCalculatorTest.powTest(PowerCalculatorTest.java:12)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- powTest -->
</testsuite> <!-- Power Cal Test -->
